export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { PlantaBaja } from './Secciones';
export { P1 } from './Secciones';
export {  P2 } from './Secciones';
export { default as NotFound } from './NotFound';
export { default as PatientList } from './PatientList';
export { default as Settings } from './Settings';
export { default as AddPaciente } from './AddPaciente';
export { default as UserList } from './UserList';
export { default as Inicio } from './Inicio';
export { default as Login } from './Login';
export { default as AddDoctor } from './AddDoctor';
